from datetime import datetime, timedelta
from models.ticket_model import TicketModel

def generate_dummy_tickets() -> list[TicketModel]:
    return [
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 5, hours = 2, minutes = 35),
                updated_date=datetime.now() - timedelta(days = 5, hours = 2, minutes = 35),
                completed=False,
                deleted=False,
                priority=3,
                ticket_type="DESIGN",
                title="Project Uno Requirements Analysis",
                description="Time allocated for meetings with Client Uno to discuss a new CMS based eCommerce online store, and documentation design.",
                initial_estimate=16.0,
                remaining_time=12.0,
                logged_time=4.0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 4, hours = 12, minutes = 50),
                updated_date=datetime.now() - timedelta(days = 4, hours = 12, minutes = 50),
                completed=False,
                deleted=False,
                priority=4,
                ticket_type="DOCUMENTATION",
                title="Document the requirements for Project Uno.",
                description="Identify any areas of development that may not be considered in the initial requirements provided by the Client.",
                initial_estimate=7.5,
                remaining_time=7.5,
                logged_time=0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 4, hours = 19, minutes = 50),
                updated_date=datetime.now() - timedelta(days = 4, hours = 19, minutes = 50),
                completed=False,
                deleted=False,
                priority=3,
                ticket_type="DEVELOPMENT",
                title="Build a proof of Concept system for Project Uno",
                description="Client Uno wants a small proof of concept to be built to showcase the system before we fully commit to building their Website from the ground up.",
                initial_estimate=37.5,
                remaining_time=37.5,
                logged_time=0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 3, hours = 6, minutes = 20),
                updated_date=datetime.now() - timedelta(days = 1),
                completed=True,
                deleted=False,
                priority=1,
                ticket_type="SUPPORT",
                title="Printer Service for Application Xeta is down.",
                description="This ticket went over. Client Xata needs their Microsoft Print Manager Service to be urgently fixed as shipping labels for products aren't printing",
                initial_estimate=4,
                remaining_time=0,
                logged_time=6,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now(),
                updated_date=datetime.now(),
                completed=False,
                deleted=True,
                priority=3,
                ticket_type="SUPPORT",
                title="Faulty Deleted",
                description="Deleted Description that requires extra text for validation",
                initial_estimate=0,
                remaining_time=0,
                logged_time=0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 2, hours = 18, minutes = 33),
                updated_date=datetime.now() - timedelta(days = 2, hours = 18, minutes = 33),
                completed=False,
                deleted=False,
                priority=3,
                ticket_type="TESTING",
                title="Testing of Client Uno's Online Shop",
                description="Time allocated for testing the functionality of the website against the defined requirements",
                initial_estimate=22.5,
                remaining_time=22.25,
                logged_time=0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 2, hours = 2, minutes = 5),
                updated_date=datetime.now(),
                completed=True,
                deleted=False,
                priority=1,
                ticket_type="SUPPORT",
                title="Emergency database restore.",
                description="This ticket will go under time. Client Alpha has botched their database and need their database to be recovered.",
                initial_estimate=4,
                remaining_time=2,
                logged_time=2,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 1, hours = 20, minutes = 55),
                updated_date=datetime.now() - timedelta(days = 1, hours = 20, minutes = 55),
                completed=False,
                deleted=False,
                priority=3,
                ticket_type="DEVELOPMENT",
                title="Primary development allocated for Client Uno's Web Shop",
                description="Time quoted for development of Client Uno's Web Shop, pending signoff after POC work is completed.",
                initial_estimate=150,
                remaining_time=150,
                logged_time=0,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(days = 1, hours = 4, minutes = 30),
                updated_date=datetime.now() - timedelta(hours = 4, minutes = 30),
                completed=False,
                deleted=False,
                priority=4,
                ticket_type="DEPLOYMENT",
                title="Set up a CI/CD Pipeline for rapid deployment of features.",
                description="Client will require continued support after the initial release of their product, we need a solid CI/CD pipeline to be able to deliver support and future development",
                initial_estimate=50,
                remaining_time=25,
                logged_time=25,
            ),
            TicketModel(
                id=None,
                created_date=datetime.now() - timedelta(hours = 12, minutes = 30),
                updated_date=datetime.now() - timedelta(hours = 6, minutes = 30),
                completed=False,
                deleted=False,
                priority=5,
                ticket_type="DEVELOPMENT",
                title="AWS Cloud environments",
                description="This ticket is massively over. Client Uno requires a Dev, Staging & Prod environment on AWS that integrates with our CI/CD pipeline. Load balancers need to be configured for horizontal scaling during promotions",
                initial_estimate=75,
                remaining_time=0,
                logged_time=105,
            )
        ]